### ISSUE TITLE
Allow tasks to have dependencies on task groups and vice versa

### ISSUE THREAD

**Issue by bishopofbathandwells** [pipeline-tools/gusty#64]
Currently, when we set a task to depend on a task group it doesn't work. Also, when setting a task group to depend on a task it doesn't work. It's not clear why either of these cases should be problematic. In fact, enjoy_breakfast.yml in the provided examples suggests their shouldn't be any issue.

Can anyone confirm whether there is some hidden complexity that I'm missing or if it should generally work as expected.

**Comment by chriscardillo** [comment]
@bishopofbathandwells thanks for sharing. I've got the following tasks:

`task_a`
```yaml
operator: airflow.operators.bash.BashOperator
bash_command: date
```

`my_group/task_b`
```yaml
operator: airflow.operators.bash.BashOperator
bash_command: date
dependencies:
  - task_a
```

Where `task_b.yml` lives inside of a folder called `my_group`.

The following graph is being rendered with no dependency issues.

<img width="523" alt="Screenshot 2024-01-17 at 11 34 57 AM" src="https://github.com/pipeline-tools/gusty/assets/38569601/ba7b05ff-8caf-4f86-a788-89557826a529">



using gusty==0.21.0 and airflow==2.8.0

Where are you running into this issue? Maybe the issue is being caused by suffixes and prefixes in the breakfast DAG?

**Comment by chriscardillo** [comment]
@bishopofbathandwells - I am going to close this issue for now because of inactivity. I apologize for not answering initially, as my notifications for this repository were not active.

You can have task groups depend on each other by specifying a `dependencies` block in the `METADATA.yml` of those task group folders.

I hope this helps.
